backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  commit_messages:
    create: Create {{collection}} “{{slug}} by {{author-login}}”
    update: Update {{collection}} “{{slug}} by {{author-login}}”
    delete: Delete {{collection}} “{{slug}} by {{author-login}}”
    uploadMedia: Upload “{{path}} by {{author-login}}” 
    deleteMedia: Delete “{{path}} by {{author-login}}” 
    openAuthoring: '{{message}}'
publish_mode: editorial_workflow
media_folder: public/media
public_folder: public
site_url: https://hcs-web-docs.netlify.app
display_url: https://hcs-web-docs.netlify.app
logo_url: https://static.hcs.net.nz/images/hcs_logo.png
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - name: website_pages
    label: "Website Pages"
    folder: "website_pages"
    media_folder: 'public/media'
    public_folder: 'public'
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Menu", name: "menu", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: website_banners
    label: "Website Banner"
    folder: "website_banner"
    media_folder: 'public/media'
    public_folder: 'public'
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page Displayed On", name: "slug", widget: "string" }
      - { label: "Start Date", name: "start_date", widget: "datetime" }
      - { label: "End Date", name: "end_date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: hoogle_pages
    label: "Hoogle Pages"
    folder: "hoogle_pages"
    media_folder: 'public/media'
    public_folder: 'public'
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }